"""
Generates pre-cached LLM briefings for the demo scenario using Claude Sonnet.

Run once when ANTHROPIC_API_KEY is available. Writes output to:
    data/scenarios/2023-west-kelowna/demo_briefing.json

The committed demo_briefing.json already contains manually crafted briefings that
match the expected output. Run this script only if the LLM prompt changes or if
you want to replace the manual text with actual Claude Sonnet output.

Usage (from repo root):
    ANTHROPIC_API_KEY=sk-... python3 backend/scripts/generate_demo_briefings.py
"""

import asyncio
import json
import os
from pathlib import Path

import anthropic

SCENARIO_DIR = Path(__file__).parents[2] / "data" / "scenarios" / "2023-west-kelowna"

SYSTEM_PROMPT = (
    "You are EMBER, an emergency evacuation assistant for BC wildfire emergencies. "
    "Given structured data about a resident's situation, generate a 3-4 sentence "
    "plain-language evacuation briefing.\n\n"
    "Be direct, specific, and actionable. Use no jargon. Include: distance to fire, "
    "time estimate, recommended route, shelter name, and any road closures to avoid. "
    "If accessibility flags are set, mention the relevant accommodation. "
    "Do not add disclaimers or caveats — the system labels projections on the map already."
)

BASE_PAYLOAD = {
    "threat": {
        "distance_km": 7.4,
        "time_to_perimeter_hours": 4.2,
        "spread_rate": "HIGH",
        "wind_speed_kmh": 42,
        "wind_direction": "NE",
    },
    "route": {
        "primary": "Hwy 97 South via Boucherie Rd",
        "distance_km": 5.8,
        "duration_min": 8,
        "fallback": "Hwy 97C West to Merritt",
    },
    "shelter": {
        "name": "Royal LePage Place",
        "address": "2760 Cameron Rd, West Kelowna",
        "status": "Open",
        "is_accessible": True,
        "has_pet_area": True,
    },
    "closures": [
        "Westside Road — CLOSED (fire activity)",
        "Bear Creek Road — CLOSED (evacuation zone)",
    ],
}

VARIANTS = {
    "default": {"mobility": False, "medical": False, "pets": False, "no_vehicle": False},
    "mobility": {"mobility": True, "medical": False, "pets": False, "no_vehicle": False},
    "medical": {"mobility": False, "medical": True, "pets": False, "no_vehicle": False},
    "pets": {"mobility": False, "medical": False, "pets": True, "no_vehicle": False},
    "no_vehicle": {"mobility": False, "medical": False, "pets": False, "no_vehicle": True},
}


async def generate_one(client: anthropic.AsyncAnthropic, key: str, profile: dict) -> str:
    payload = {**BASE_PAYLOAD, "profile": profile}
    msg = await client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=256,
        system=SYSTEM_PROMPT,
        messages=[{"role": "user", "content": json.dumps(payload, indent=2)}],
    )
    return msg.content[0].text.strip()


async def main():
    api_key = os.getenv("ANTHROPIC_API_KEY")
    if not api_key:
        print("ERROR: ANTHROPIC_API_KEY not set")
        return

    client = anthropic.AsyncAnthropic(api_key=api_key)
    briefings = {}

    for key, profile in VARIANTS.items():
        print(f"  Generating: {key} ...", end=" ", flush=True)
        text = await generate_one(client, key, profile)
        briefings[key] = text
        print("done")

    out = {
        "metadata": {
            "description": "Pre-generated LLM briefings for 2023 McDougall Creek fire demo scenario",
            "generated_for": "1240 Marble Terrace, West Kelowna, BC",
            "fire_conditions": "Aug 17 2023, 7PM, ISI 24.4, wind 42 km/h NE",
            "notes": "Generated by backend/scripts/generate_demo_briefings.py. Regenerate if LLM prompt changes.",
        },
        "briefings": briefings,
    }

    out_path = SCENARIO_DIR / "demo_briefing.json"
    with open(out_path, "w") as f:
        json.dump(out, f, indent=2)
    print(f"Written to {out_path}")


if __name__ == "__main__":
    asyncio.run(main())
