"""
Generates demo_route.json with a real driving route from the demo address to
Royal LePage Place via the Mapbox Directions API. One-shot dev-time script —
result is committed to git and loaded statically at demo time.

Output: data/scenarios/2023-west-kelowna/demo_route.json

Input:  MAPBOX_TOKEN in backend/.env

Usage (from repo root):
    python3 backend/scripts/generate_demo_route.py
"""

from __future__ import annotations

import json
import math
import os
import sys
from pathlib import Path

import httpx
from dotenv import load_dotenv

load_dotenv(Path(__file__).parents[1] / ".env")

REPO_ROOT = Path(__file__).parents[2]
SCENARIO_DIR = REPO_ROOT / "data" / "scenarios" / "2023-west-kelowna"
OUTPUT_FILE = SCENARIO_DIR / "demo_route.json"

DIRECTIONS_URL = "https://api.mapbox.com/directions/v5/mapbox/driving/{coords}"

# Demo origin: 1598 Westlake Rd, West Kelowna, BC
ORIGIN = {"lat": 49.889862, "lng": -119.554390, "address": "1598 Westlake Rd, West Kelowna, BC V1Z 3H5"}

# Destination: Royal LePage Place (shelter_001)
DEST = {"lat": 49.8587, "lng": -119.5827, "address": "2760 Cameron Road, West Kelowna, BC V1Z 2T6"}


def encode_polyline(coords: list[list[float]]) -> str:
    """Encodes a list of [lng, lat] pairs into a Google-compatible encoded polyline."""
    result = []
    prev_lat = prev_lng = 0
    for lng, lat in coords:
        lat_e5 = round(lat * 1e5)
        lng_e5 = round(lng * 1e5)
        d_lat = lat_e5 - prev_lat
        d_lng = lng_e5 - prev_lng
        prev_lat = lat_e5
        prev_lng = lng_e5
        for val in (d_lat, d_lng):
            val = ~(val << 1) if val < 0 else val << 1
            while val >= 0x20:
                result.append(chr((val & 0x1F) + 63 + 0x20))
                val >>= 5
            result.append(chr(val + 63))
    return "".join(result)


def main() -> int:
    token = os.getenv("MAPBOX_TOKEN", "").strip()
    if not token:
        print("ERROR: MAPBOX_TOKEN not set in backend/.env", file=sys.stderr)
        return 1

    coords_str = f"{ORIGIN['lng']},{ORIGIN['lat']};{DEST['lng']},{DEST['lat']}"
    url = DIRECTIONS_URL.format(coords=coords_str)
    params = {
        "geometries": "geojson",
        "overview": "full",
        "access_token": token,
    }

    print(f"Requesting route: {ORIGIN['address']} → {DEST['address']}")
    resp = httpx.get(url, params=params, timeout=30.0)
    resp.raise_for_status()
    data = resp.json()

    if data.get("code") != "Ok" or not data.get("routes"):
        print(f"ERROR: no route returned (code={data.get('code')})", file=sys.stderr)
        return 1

    route = data["routes"][0]
    geojson_coords = route["geometry"]["coordinates"]  # [[lng, lat], ...]
    distance_km = round(route["distance"] / 1000, 1)
    duration_min = round(route["duration"] / 60)

    # Google-encoded polyline for the frontend's decodePolyline()
    polyline = encode_polyline(geojson_coords)

    # Build the route summary from Mapbox legs
    legs = route.get("legs", [])
    summary = legs[0].get("summary", "Route to Royal LePage Place") if legs else "Route to Royal LePage Place"
    if not summary:
        summary = "Route to Royal LePage Place"

    out = {
        "metadata": {
            "description": "Pre-computed demo route for 2023 McDougall Creek fire scenario",
            "origin_address": ORIGIN["address"],
            "origin_lat": ORIGIN["lat"],
            "origin_lng": ORIGIN["lng"],
            "notes": "Generated by backend/scripts/generate_demo_route.py via Mapbox Directions API. Polyline is Google Maps encoded format.",
        },
        "primary": {
            "summary": summary if summary != "" else "Hwy 97 S via Boucherie Rd",
            "distance_km": distance_km,
            "duration_min": duration_min,
            "polyline": polyline,
        },
        "fallback": {
            "summary": "Hwy 97C West to Merritt",
            "distance_km": 85.0,
            "duration_min": 55,
        },
        "shelter_drive_times": {
            "shelter_001": duration_min,
            "shelter_002": 65,
            "shelter_003": 55,
            "shelter_004": 15,
            "shelter_005": 18,
        },
    }

    with open(OUTPUT_FILE, "w") as f:
        json.dump(out, f, indent=2)
    print(f"  wrote {OUTPUT_FILE.relative_to(REPO_ROOT)}")

    print(f"\nRoute: {summary}")
    print(f"  {distance_km} km, ~{duration_min} min")
    print(f"  {len(geojson_coords)} vertices in polyline")
    print(f"  start: ({geojson_coords[0][1]:.5f}, {geojson_coords[0][0]:.5f})")
    print(f"  end:   ({geojson_coords[-1][1]:.5f}, {geojson_coords[-1][0]:.5f})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
